language: python
python:
  - '3.4'
install:
  - pip install -r requirements.txt
script:
 - mypy -m main
 - cd src && mypy -m chatstack
 - python -W default::Warning -m coverage run --branch -m pytest --tb short
 - python -m coverage report --include 'chatstack/*'
